### ISSUE TITLE
Cannot open youtube page

### ISSUE THREAD

**Issue by testn** [slashlos/Helium#18]
It shows the following error message when trying to view a video.

An error occurred. Please try again later.

**Comment by slashlos** [comment]
Do you have a reproducer ?  What version - mac,helium involved ?

**Comment by ssetti** [comment]
I have a similar issue, can open youtube page and search for videos and am able to play it.  But I cannot play videos by pasting a direct link... It gives me an error message... An error occurred. Please try again later. (Playback ID: cJOMvEtMLAvrvhDk) 
Learn More

I am on Mojave 10.14.4, Helium version 3, build 4125

**Comment by slashlos** [comment]
So I use contextual menu (or %L) to load - youtube.com; then search your playback ID 

![Screen Shot 2019-05-10 at 10 17 22 AM](https://user-images.githubusercontent.com/3155005/57533972-f6448c00-730c-11e9-8af9-34bd792a7f2c.png)

then click first video; go back, click on 2nd; seems ok ?  btw I'm not logged into Youtube account.

**Comment by CoVoCre** [comment]
So the fact that it fails when accessing the youtube video url directly is normal for this version, it doesn't work ? 
Because for how I wanted to use it, that's basically the only way !
So for any youtube video, do : Helium, Open, URL, and the error is : 
<img width="479" alt="Capture d’écran 2019-07-01 à 11 13 37" src="https://user-images.githubusercontent.com/25605953/60424750-4ba46780-9bf1-11e9-95d8-52e5d45332bb.png">
That is, with magic url redirect on, otherwise the page does load up. But since we can't make it full window from the youtube player, it isn't supported apparently, there's no way to have a windows with just the video, except by resizing perfectly for every video... !

**Comment by slashlos** [comment]
Ah, the YouTube link has bits that might be getting clipped by Helium url fixer; can you disable 'Magic URL Redirects' preference?   If I do that, pasting a link in the URL dialog from the address bar from Safari / Chrome, it works.   If yes for you, then perhaps this global preference should be a per-document attribute ?

**Comment by slashlos** [comment]
I'm working towards a copy/paste with build 4389 and beyond to allow easy transition; eventually dragging a link onto a Helium window.

**Comment by slashlos** [comment]
This issue appears resolved as of build 4389.  I can drag a link from another web browser's address bar onto a Helium window and it shows fine; for YouTube this includes its search results and follow its search links and use middle button to launch new windows.
