### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by tmmlo** [slashlos/Helium#7]
Hi Carlos, I wanted to say first of all thank you for working on this branched version of Helium, and second, maybe I suggest some functions that I imagine would be quite helpful? 

• Able to hide the app from the Dock if it's in the menubar.
• Able to make the browser window disappear to 0%
• Able to show the browser and hide it, based on shortcute/function key/etc
• Able to show and hide the browser perhaps by clicking on the menu bar
• At the moment it seems it can't remember the size and location of the window after quit

Thank you!

**Comment by slashlos** [comment]
Ok, hiding window(s) toggle is achieved by pressing control-option-command; however affecting audio or playback programmatically is currently not feasible.  Still addressing issue re: layout which also affects full screen mode.

**Comment by tmmlo** [comment]
That's great! Is it possible to get an updated version to play around with?

**Comment by slashlos** [comment]
These issues were addressed in an uploaded noted in [feature#4 May'15](https://github.com/slashlos/Helium/issues/4#issuecomment-389239490) comment.

As document windows remember where they were there was not really a change needed here but we're trying to track this so that when a play item or list is played, it will resume its attributes.
